image:
  file: Dockerfile
ports:
- port: 6080
  onOpen: notify
- port: 5900
  onOpen: ignore
tasks:
- command: >
    mkdir --parents build &&
    cd build &&
    cmake .. &&
    make &&
    ./sdl2-demo
    cd ..
